export default {
  SetUserBalance: {
    SET_USER_BALANCE_SUCCESS: 'SET_USER_BALANCE_SUCCESS',
  },
  SetWalletConnected: {
    SET_WALLET_CONNECTED_SUCCESS: 'SET_WALLET_CONNECTED_SUCCESS',
  },
  SetWalletDisconnected: {
    SET_WALLET_DISCONNECTED_SUCCESS: 'SET_WALLET_DISCONNECTED_SUCCESS',
  },
  SetProvider: {
    SET_PROVIDER_SUCCESS: 'SET_PROVIDER_SUCCESS',
  },
  SetContracts: {
    SET_CONTRACTS_REQUEST: 'SET_CONTRACTS_REQUEST',
    SET_CONTRACTS_SUCCESS: 'SET_CONTRACTS_SUCCESS',
    SET_CONTRACTS_FAIL: 'SET_CONTRACTS_FAIL',
    SET_CONTRACTS_PENDING: 'SET_CONTRACTS_PENDING',
  },
  SetWalletAddress: {
    SET_WALLET_ADDRESS_SUCCESS: 'SET_WALLET_ADDRESS_SUCCESS',
  },
};
